# Generated by Django 2.2.5 on 2019-09-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190921_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('*', '1'), ('**', '2'), ('***', '3'), ('****', '4'), ('*****', '5')], max_length=5),
        ),
    ]
