# Generated by Django 2.2.5 on 2019-09-24 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190924_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('special_acces', 'Can read all reviews')]},
        ),
    ]
