# Generated by Django 2.2.5 on 2019-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20190921_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('*', '1'), (' * * ', '2'), (' * * * ', '3'), (' * * * * ', '4'), (' * * * * * ', '5')], max_length=5),
        ),
    ]
