# Generated by Django 2.2.5 on 2019-09-25 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190924_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('special_acces', 'Can read all reviews')], 'verbose_name': 'Review'},
        ),
    ]
