# Generated by Django 2.2.5 on 2019-09-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20190925_1047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('special_acces', 'can read all reviews')], 'verbose_name': 'Review'},
        ),
    ]
