# Generated by Django 2.2.5 on 2019-09-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20190925_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'permissions': [('special_access', 'can read all reviews')], 'verbose_name': 'Review'},
        ),
    ]
